### ISSUE TITLE
Regression - rekall 1.4.0 tracebacks with GrrCON-2012's memdump.img

### ISSUE THREAD

**Issue by ant1** [google/rekall#79] opened 2015-08-16 16:47 UTC
With rekall 1.4.0,  I have the following traceback with GrrCON-2012's memdump.img
With rekall 1.3.2 it was working fine

```
rekall 1.3.2
[1] memdump.img 16:39:55> imageinfo
------------------------> imageinfo()
        Fact                     Value             
-------------------- ------------------------------
Kernel DTB           0x39000                       
NT Build             2600.xpsp.080413-2111         
NT Build Ex          -                             
Signed Drivers       -                             
Time (UTC)           2012-04-28 02:23:21+0000      
Time (Local)         2012-04-28 06:23:21+0000      
Sec Since Boot       1615.703125                   
NtSystemRoot         C:\WINDOWS                    

**************** Physical Layout ****************
Phys Start  Phys End  Number of Pages
---------- ---------- ---------------
0x00001000 0x0009f000 158            
0x00100000 0x00fff000 3839           
0x01000000 0x1fef0000 126704         
0x1ff00000 0x20000000 256            
                   Out<3> Plugin: imageinfo
```

```
rekall 1.4.0
[1] memdump.img 16:44:55> imageinfo
------------------------> imageinfo()
        Fact                     Value
-------------------- ------------------------------
Kernel DTB           0x39000
CRITICAL:rekall.1:Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/rekall/session.py", line 706, in RunPlugin
    result = plugin_obj.render(ui_renderer) or plugin_obj
  File "/usr/local/lib/python2.7/site-packages/rekall/plugins/windows/misc.py", line 216, in render
    desc, self.profile.get_constant_object(name, target=type))
  File "/usr/local/lib/python2.7/site-packages/rekall/obj.py", line 2140, in get_constant_object
    offset = self.get_constant(constant, is_address=True)
  File "/usr/local/lib/python2.7/site-packages/rekall/plugins/overlays/basic.py", line 1020, in get_constant
    return base_constant + self.GetImageBase()
  File "/usr/local/lib/python2.7/site-packages/rekall/plugins/overlays/windows/windows.py", line 133, in GetImageBase
    self.session.GetParameter("kernel_base"))
  File "/usr/local/lib/python2.7/site-packages/rekall/session.py", line 610, in GetParameter
    result = self._RunParameterHook(item)
  File "/usr/local/lib/python2.7/site-packages/rekall/session.py", line 645, in _RunParameterHook
    result = hook.calculate()
  File "/usr/local/lib/python2.7/site-packages/rekall/plugins/windows/kernel.py", line 129, in calculate
    for hit in scanner.scan(offset=kernel_boundary, maxlen=maxlen):
  File "/usr/local/lib/python2.7/site-packages/rekall/scan.py", line 309, in scan
    for run in self.address_space.get_address_ranges(start=offset, end=end):
  File "/usr/local/lib/python2.7/site-packages/rekall/addrspace.py", line 175, in get_address_ranges
    start=start, end=end):
  File "/usr/local/lib/python2.7/site-packages/rekall/addrspace.py", line 200, in _get_address_ranges
    start=start):
  File "/usr/local/lib/python2.7/site-packages/rekall/plugins/addrspaces/intel.py", line 360, in get_available_addresses
    pde_addr = ((self.pte_value & 0xfffff000) |
AttributeError: 'IA32PagedMemory' object has no attribute 'pte_value'

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
```

Some other plugins like connscan or connections that used to work no longer work too

**Comment by scudette** [comment] 2015-08-17 17:57
Thanks for testing this. The problem is with the non-pae version of the I386 address spaces. We dont really see many images like that any more (x86 non pae) except for very ancient ones which is why this escaped testing :-).

I had a quick look at the data structures which seem to be different enough that some effort will be required to support pagefile analysis on such an old XP version. I dont think we care too much about such an old XP version so we will just support the normal hardware page translation without all the advanced stuff (like prototypes, pagefile, mapped files etc) which is available for later windows versions.

Fix is under review at
https://codereview.appspot.com/258290043/

**Comment by chrisbdaemon** [comment] 2015-09-01 17:55
I just ran into this as well trying to run the pslist plugin against a Digital Corpora image:

http://digitalcorpora.org/corp/nps/scenarios/2009-m57-patents/ram/charlie-2009-12-11.mddramimage.zip

**Comment by scudette** [comment] 2015-09-01 18:56
This is already fixed in rekall head... We hope to release again very soon
:-).

**Comment by chrisbdaemon** [comment] 2015-09-01 19:07
Should this issue be closed then?

**Comment by scudette** [comment] 2015-09-01 19:09
Yes you are probably right :-) thanks for reporting!

**Closed by scudette** 2015-09-01 19:09 UTC

**Comment by chrisbdaemon** [comment] 2015-09-01 19:10
Cool, hope I didn't come across as knit-picking.  I think I might have more to report in a bit.

**Comment by scudette** [comment] 2015-09-01 19:23
No problems! Thanks for the report. We realize that we need to press a 1.4.1 release soon to fix some bugs and to add some of the features which didn't make it to the 1.4.0 release. We appreciate the bug reports!
