### ISSUE TITLE
Rekall 1.7.2 Windows Binary is Broken

### ISSUE THREAD

**Issue by dsweet04** [google/rekall#335] opened 2017-12-12 18:24 UTC
Tested installing Rekall using the 1.7.2 binary on windows 7 and windows 10 and on both systems any command run produces the following error.
<img width="465" alt="screen shot 2017-12-12 at 1 20 35 pm" src="https://user-images.githubusercontent.com/5368247/33901390-aa842f30-df3f-11e7-8ebe-54510b25adb9.png">

The current binary is broken.

**Comment by scudette** [comment] 2017-12-13 18:37
I tried to grab a couple of cloud VMs but could not reproduce this problem - maybe these standard images already come with the VS redistributable. 

A google search shows similar issues with other projects:
https://bugs.documentfoundation.org/show_bug.cgi?id=108580

I think reading https://blogs.msdn.microsoft.com/vcblog/2015/03/03/introducing-the-universal-crt/ we can just copy all these files and it should work:

Updated September 11, 2015:  App-local deployment of the Universal CRT is supported.  To obtain the binaries for app-local deployment, install the Windows Software Development Kit (SDK) for Windows 10.  The binaries will be installed to C:\Program Files (x86)\Windows Kits\10\Redist\ucrt.  You will need to copy all of the DLLs with your app (note that the set of DLLs are necessary is different on different versions of Windows, so you must include all of the DLLs in order for your program to run on all supported versions of Windows). 

[x64.zip](https://github.com/google/rekall/files/1556576/x64.zip)

I zipped up all these files, can you please check if it works on one of these machines if these files are dropped in the installation directory?

**Comment by dsweet04** [comment] 2017-12-14 16:38
After dropping in those files it worked as expected on both windows 7 and 10

**Comment by scudette** [comment] 2017-12-14 17:15
Thanks Daniel for testing this. I will update the binaries later today.

**Comment by scudette** [comment] 2017-12-15 04:13
Ok Im just leaving this here for documentation. There is a detailed explanation of what these dlls are here:

https://github.com/pyinstaller/pyinstaller/issues/1566

If one installs "Windows Software Development Kit (SDK) for Windows 10" it break building of python modules because that (3.5Gb) kit somehow interferes with the normal compilers. The below works fine before installing the SDK. This is the error:

```
(Dev36) C:\Users\test\projects\rekall>pip install --no-binary :all:  -I rekall-capstone
Collecting rekall-capstone
  Using cached rekall-capstone-3.0.5.post2.zip
Skipping bdist_wheel for rekall-capstone, due to binaries being disabled for it.
Installing collected packages: rekall-capstone
  Running setup.py install for rekall-capstone ... error
....
    Finished generating code
    LINK : fatal error LNK1158: cannot run 'rc.exe'
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\link.exe' failed with exit status 1158

    ----------------------------------------
Command "c:\users\test\dev36\scripts\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\test\\AppData\\Local\\Temp\\pip-build-zg6x98ue\\rekall-capstone\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\test\AppData\Local\Temp\pip-j40o7n71-record\install-record.txt --single-version-externally-managed --compile --install-headers c:\users\test\dev36\include\site\python3.6\rekall-capstone" failed with error code 1 in C:\Users\test\AppData\Local\Temp\pip-build-zg6x98ue\rekall-capstone\
```

Yes - the new compiler removes rc.exe and cant find it again - sigh. So I needed to copy the rc.exe and dll from the kit to the C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\\BIN\x86_amd64\ path. This fixes building of python modules.

I rebuilt the windows binary using the winbuild.py script and uploaded the new binaries to the release.

**Closed** 2018-01-29 06:33 UTC
